Use bcrypt with password_hash (#35)
Changes:

- Reinstate the `bcrypt` option for `password_hash`

This has been done since `node_exporter` expects hashed password for
basic authentication to be created with `brypt`. I initially removed
because the following appears when running the `monitoring_client` role:

```
AttributeError: module 'bcrypt' has no attribute '__about__'
```

The play proceeds and `node_exporter` is correctly installed. I tried
pinning `bcrypt` to `4.0.1` as suggested in
https://github.com/pyca/bcrypt/issues/684 but the traceback still
appears. Without `bcrypt` the `node_exporter` service fails to start.